package com.example.domin.models

data class Series(
    val backdropPath: String,
    val createdBy: List<String>,
    val episodeRunTime: List<Int>,
    val firstAirDate: String,
    val genres: List<GenreSeries>,
    val homepage: String,
    val id: Int,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastEpisodeToAir: String,
    val name: String,
    val networks: List<String>,
    val nextEpisodeToAir: String,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val productionCompanies: List<String>,
    val productionCountries: List<String>,
    val seasons: List<String>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Double,
    val voteCount: Int
)
